export type City = "hyderabad" | "bengaluru";

export type Center = {
  id: string;
  name: string;
  address: string;
  pincode: string;
  lat: number;
  lng: number;
  city: City;
};

export const CITY_TABS: { id: City; label: string }[] = [
  { id: "hyderabad", label: "Hyderabad" },
  { id: "bengaluru", label: "Bengaluru" },
];

export const BODHI_CENTERS: Center[] = [
  {
    id: "alwal",
    name: "Alwal",
    address: "Saraswathi Colony, Alwal, Secunderabad, Hyderabad",
    pincode: "500010",
    lat: 17.5100,
    lng: 78.5092,
    city: "hyderabad",
  },
  {
    id: "alwal-hills",
    name: "Alwal Hills",
    address: "Old Alwal, Secunderabad, Hyderabad",
    pincode: "500010",
    lat: 17.5034,
    lng: 78.5114,
    city: "hyderabad",
  },
  {
    id: "bachupally",
    name: "Bachupally",
    address: "Bachupally, Hyderabad",
    pincode: "500090",
    lat: 17.541,
    lng: 78.3691,
    city: "hyderabad",
  },
  {
    id: "bandlaguda",
    name: "Bandlaguda",
    address: "Bandlaguda, Hyderabad",
    pincode: "500005",
    lat: 17.3486,
    lng: 78.4953,
    city: "hyderabad",
  },
  {
    id: "beeramguda",
    name: "Beeramguda",
    address: "Beeramguda, Hyderabad",
    pincode: "502032",
    lat: 17.4924,
    lng: 78.3142,
    city: "hyderabad",
  },
  {
    id: "chandanagar",
    name: "Chandanagar",
    address: "Chanda Nagar, Hyderabad",
    pincode: "500050",
    lat: 17.4948,
    lng: 78.3214,
    city: "hyderabad",
  },
  {
    id: "esi-erragadda",
    name: "ESI, Erragadda",
    address: "ESI, Erragadda, Hyderabad",
    pincode: "500038",
    lat: 17.4574,
    lng: 78.4365,
    city: "hyderabad",
  },
  {
    id: "hsr-layout",
    name: "HSR Layout",
    address: "HSR Layout, Bengaluru",
    pincode: "560102",
    lat: 12.9116,
    lng: 77.6473,
    city: "bengaluru",
  },
  {
    id: "indiranagar",
    name: "Indiranagar",
    address: "Indiranagar, Bengaluru",
    pincode: "560038",
    lat: 12.9784,
    lng: 77.6408,
    city: "bengaluru",
  },
  {
    id: "khairatabad",
    name: "Khairatabad, Hyderabad",
    address: "Khairatabad, Hyderabad",
    pincode: "500004",
    lat: 17.4144,
    lng: 78.4622,
    city: "hyderabad",
  },
  {
    id: "kphb",
    name: "KPHB, Hyderabad",
    address: "KPHB, Hyderabad",
    pincode: "500072",
    lat: 17.4849,
    lng: 78.3914,
    city: "hyderabad",
  },
  {
    id: "manikonda",
    name: "Manikonda",
    address: "Manikonda, Hyderabad",
    pincode: "500089",
    lat: 17.4004,
    lng: 78.3689,
    city: "hyderabad",
  },
  {
    id: "matrusri-nagar",
    name: "Matrusri Nagar",
    address: "Matrusri Nagar, Hafeezpet, Hyderabad",
    pincode: "500049",
    lat: 17.4924,
    lng: 78.3678,
    city: "hyderabad",
  },
  {
    id: "nallagandla",
    name: "Nallagandla",
    address: "Nallagandla, Hyderabad",
    pincode: "500046",
    lat: 17.4656,
    lng: 78.3094,
    city: "hyderabad",
  },
  {
    id: "nizampet",
    name: "Nizampet",
    address: "Nizampet, Hyderabad",
    pincode: "500085",
    lat: 17.5028,
    lng: 78.3851,
    city: "hyderabad",
  },
  {
    id: "pragathi-nagar",
    name: "Pragathi Nagar",
    address: "Pragathi Nagar, Hyderabad",
    pincode: "500090",
    lat: 17.5221,
    lng: 78.3962,
    city: "hyderabad",
  },
  {
    id: "raghavendra-nagar-kondapur",
    name: "Raghavendra Nagar, Kondapur",
    address: "Raghavendra Nagar, Kondapur, Hyderabad",
    pincode: "500084",
    lat: 17.4654,
    lng: 78.3543,
    city: "hyderabad",
  },
  {
    id: "sanikpuri",
    name: "Sanikpuri",
    address: "Sainikpuri, Secunderabad, Hyderabad",
    pincode: "500094",
    lat: 17.4945,
    lng: 78.5455,
    city: "hyderabad",
  },
  {
    id: "suchitra",
    name: "Suchitra",
    address: "Suchitra, Hyderabad",
    pincode: "500067",
    lat: 17.5127,
    lng: 78.4745,
    city: "hyderabad",
  },
  {
    id: "vasanth-nagar",
    name: "Vasanth Nagar",
    address: "Vasanth Nagar, Kukatpally, Hyderabad",
    pincode: "500085",
    lat: 17.4901,
    lng: 78.3827,
    city: "hyderabad",
  },
];
